# GLOBAL

# Package Overview
package_name: zanasonic_etl

# to set the random seed
random_state: 42

# PRICE PAID DATA

price_paid_raw_data: ./../../data/raw/pp_sample.csv
price_paid_processed_data: ./../../data/processed/pp_sample.parquet

price_paid_columns:
    - id
    - price
    - date
    - postcode
    - type
    - new_build
    - land
    - primary_address
    - secondary_address
    - street
    - locality
    - town_city
    - district
    - county
    - ppd
    - record

price_paid_date_column:
  - date

price_paid_min_price: 10000
price_paid_max_price: 5000000


price_paid_columns_to_drop:
  - locality
  - town_city
  - district
  - county

# HOUSE PRICE INDEX DATA

hpi_raw_data: ./../../data/raw/house_price_index.csv
hpi_processed_data: ./../../data/processed/house_price_index.parquet

hpi_columns:
  - date
  - regionname
  - areacode
  - index
  - detachedindex
  - semidetachedindex
  - terracedindex
  - flatindex

hpi_rename_columns:
  regionname: region_name
  areacode: area_code
  detachedindex: detached_index
  semidetachedindex: semi_detached_index
  terracedindex: terraced_index
  flatindex: flat_index

# POSTCODE DATA

postcode_raw_data: ./../../data/raw/postcodes.csv
postcode_processed_data: ./../../data/processed/postcode.parquet
