# GLOBAL

# Package Overview
package_name: zanasonic
package_version: 0.1.0-beta

# to set the random seed
random_state: 42

# PRICE PAID DATA

price_paid_raw_data: ./data/raw/pp-complete.csv
price_paid_processed_data: ./data/processed/pp_sample.parquet
price_paid_master_processed_data: ./data/processed/pp_master.parquet
price_paid_google_drive_raw_data: https://drive.google.com/file/d/1aVFQF0wjq9IMzH9H8PRYjxCZuDzEl3Fp/view?usp=sharing

price_paid_columns:
    - id
    - price
    - date
    - postcode
    - type
    - new_build
    - land
    - primary_address
    - secondary_address
    - street
    - locality
    - town_city
    - district
    - county
    - ppd
    - record

price_paid_date_column:
  - date

price_paid_min_price: 10000
price_paid_max_price: 5000000


price_paid_columns_to_drop:
  - locality
  - town_city
  - district
  - county

# HOUSE PRICE INDEX DATA

hpi_raw_data: ./data/raw/house_price_index.csv
hpi_processed_data: ./data/processed/house_price_index.parquet
hpi_google_drive_raw_data: https://drive.google.com/file/d/1HZE8GwM4S45IMvGo7FkNCXtUhTIJWRkh/view?usp=sharing

hpi_columns:
  - date
  - regionname
  - areacode
  - index
  - detachedindex
  - semidetachedindex
  - terracedindex
  - flatindex

hpi_rename_columns:
  regionname: region_name
  areacode: area_code
  detachedindex: detached_index
  semidetachedindex: semi_detached_index
  terracedindex: terraced_index
  flatindex: flat_index

# POSTCODE DATA

postcode_raw_data: ./data/raw/postcodes.csv
postcode_processed_data: ./data/processed/postcode.parquet
postcode_google_drive_raw_data: https://drive.google.com/file/d/1ttoxcjiQMBbT1xWGocTGbi2cYH5YV06f/view?usp=sharing

data:
